"""update user fields

Revision ID: af89171e47a9
Revises: f03b65bd932e
Create Date: 2025-06-08 17:23:49.399101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af89171e47a9'
down_revision: Union[str, None] = 'f03b65bd932e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('permissions')
    op.drop_table('sessions')
    op.drop_table('roles')
    op.drop_table('role_permissions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_permissions',
    sa.Column('role_id', sa.NUMERIC(), nullable=True),
    sa.Column('permission_id', sa.NUMERIC(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], )
    )
    op.create_table('roles',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('scope', sa.VARCHAR(length=14), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sessions',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('user_id', sa.NUMERIC(), nullable=True),
    sa.Column('user_agent', sa.VARCHAR(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permissions',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('action', sa.VARCHAR(), nullable=True),
    sa.Column('resource_id', sa.NUMERIC(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(), nullable=True),
    sa.Column('mnemonic_hash', sa.VARCHAR(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=1)
    op.create_table('user_roles',
    sa.Column('user_id', sa.NUMERIC(), nullable=False),
    sa.Column('role_id', sa.NUMERIC(), nullable=False),
    sa.Column('scope_id', sa.NUMERIC(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    # ### end Alembic commands ###
